//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BWSolver.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BWSOLVER_DIALOG             102
#define IDS_FILELOADPROMPT              102
#define IDR_MAINFRAME                   128
#define IDI_BOXICON                     136
#define IDI_EMPTYICON                   137
#define IDI_MANICON                     138
#define IDI_REDBOXICON                  139
#define IDI_SPOTICON                    140
#define IDI_WALLICON                    141
#define IDI_SPOTMANICON                 143
#define IDC_BUTTONSOLVE                 1000
#define IDC_BUTTON2                     1001
#define IDC_LOADWORLD                   1001
#define IDC_WORLD                       1004
#define IDC_PALETTE                     1006
#define IDC_CUSTOM3                     1009
#define IDC_RICHEDIT1                   1010
#define IDC_FRAMENUMBER                 1021
#define IDC_FRAMESLIDER                 1024
#define IDC_MAXDEPTH                    1025
#define IDC_MAXDEPTHSPIN                1029
#define IDC_SOLUTIONPROGRESS            1038
#define IDC_INFORMATION                 1040
#define IDC_PRIORITY                    1041

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
